### ISSUE TITLE
updateClass function (Adding Multiple Classes)

### ISSUE THREAD

**Issue by btraxinger** [BakedSoftware/Silica#1]
I attempted to return a string value from my controller to a data-class on a view that included two classes. Silica gave me an error saying that HTML space elements were not allowed which prevented me from adding two classes. 

I was able to resolve the issue by modifying the updateClass function as follows:

if (klass) {
  var newKlasses = klass.split(" ");
    for(var k of newKlasses){
        element.classList.add(k);
    }
}

I was wondering if your implementation was intentional, or if I could continue to use the modified method above without harm.

**Comment by kayleg** [comment]
It was slightly intentional for performance. Let me know if the following works for you and I will include it.

Return a `single class` as a **string** or `multiple classes` as an **array**

```
        if (klass)
        {
          if (klass instanceof Array)
          {
            element.classList.add.apply(element.classList, klass);
          }
          else
          {
            element.classList.add(klass);
          }
        }
```

**Comment by btraxinger** [comment]
That works perfectly, thank you :+1:
