### ISSUE TITLE
ENV Vars / Template

### ISSUE THREAD

**Issue by mrz1836** [BakedSoftware/silica#4]
It would be super cool if Silica could take an env file and replace the variables in the app.js code - supports multiple environments without exposing env vars that are not needed.

**Comment by kayleg** [comment]
I added support for this at build time using either `silica watch` or `silica build`

The syntax is `${ENV_VAR_NAME}` and `${ENV_VAR_NAME:=default}` where `default` is a value to use when the env is missing the variable. 

The envs can be used in the following places:

* `index.html`
* Any view included into the index.html file at compile time (`data-include`)
* `app.js`
* Any Javascript file included into the `app.js` file at compile time (`import...`)
